inherit_from:
  - rubocop-todo.yml

AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

# "Use alias_method instead of alias"
# We're fine with `alias`.
Alias:
  Enabled: false

AlignParameters:
  Enabled: true
  EnforcedStyle: with_first_parameter

# Warns when the class is excessively long.
ClassLength:
  Max: 118 # RaiseError matcher.

# "Avoid the use of the case equality operator ==="
# We prefer using `Class#===` over `Object#is_a?` because `Class#===`
# is less likely to be monkey patched than `is_a?` on a user object.
CaseEquality:
  Enabled: false

CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: 'inject'

DoubleNegation:
  Enabled: false

# As long as we support ruby 1.8.7 we have to use hash rockets.
HashSyntax:
  EnforcedStyle: hash_rockets
